version: '3.8'

services:
  icommerce:
    image: icommerce:latest
    container_name: icommerce
    environment:
      - eureka.client.serviceUrl.defaultZone = http://172.17.0.1:8761/eureka/
    ports:
      - 8081:8081
    networks:
      - icommercenetwork

networks:
  icommercenetwork:
    driver: bridge
