version: '3.8'

services:
  icommerce:
    image: icommerce
    container_name: icommerce
    ports:
      - 8081:8081
    networks:
      - icommerce_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  icommerce_network:
    driver: bridge
